# General
name: hytale
labels: {}
# Hytale Server Configuration
image:
  repository: ghcr.io/sakulflee/hytale
  tag: latest
  pullPolicy: IfNotPresent
# Service Configuration
service:
  type: LoadBalancer
  port: 5520
  udpPort: 520
# Resources
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi
# JVM Configuration
jvm:
  additionalOptions:
    - "-server"
    - "-XX:+UseG1GC"
    - "-XX:+UseStringDeduplication"
    - "-Xmx4G"
    - "-Xms512M"
    - "-server"
# Storage Configuration
persistence:
  size: 10Gi
  storageClass: ""
# Credentials
credentials:
  secretName: "hytale-credentials"
  credentialsKey: "credentials.json"
# Security
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
# Probes
probes:
  readiness:
    initialDelaySeconds: 300
    periodSeconds: 30
  liveness:
    initialDelaySeconds: 300
    periodSeconds: 30
