apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  # serviceName is removed as it is specific to StatefulSets
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: hytale-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true
          tty: true
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: UDP
              name: game-udp
          env:
            - name: JAVA_OPTIONS
              value: {{ .Values.jvm.additionalOptions | join " " }}
            - name: MODS
              value: {{ .Values.mods | join " " }}
          volumeMounts:
            - name: data-storage
              mountPath: /opt/hytale
            - name: logs-storage
              mountPath: /opt/hytale/Server/logs
            - name: credentials-volume
              mountPath: /opt/hytale-downloader-secret
              subPath: .hytale-downloader-credentials.json
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
          startupProbe:
            exec:
              command:
                - cat
                - {{ .Values.probes.startup.file }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-pvc" .Values.name) }}
        - name: logs-storage
          emptyDir: {}
        - name: credentials-volume
          secret:
            secretName: {{ .Values.credentials.secretName }}
            items:
              - key: {{ .Values.credentials.credentialsKey }}
                path: .hytale-downloader-credentials.json
            optional: true
