apiVersion: v1
kind: Service
metadata:
  name: {{ include "hytale-server.fullname" . }}
  labels:
    {{- include "hytale-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
      name: game-udp
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}
  selector:
    {{- include "hytale-server.selectorLabels" . | nindent 4 }}
