apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:  
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
      name: hytale-udp
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}

