name: CI and Release Helm Chart
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Lint and Package
        run: |
          # Lint and package to identify issues
          helm lint .
          helm package .
      - name: Login to GHCR
        # Only login if we are pushing a tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
          --username ${{ github.actor }} --password-stdin
      - name: Publish to GHCR
        # Only publish if we are pushing a tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REGISTRY_URL="oci://ghcr.io/$REPO_OWNER/charts"

          # Find the generated .tgz file
          CHART_PACKAGE=$(ls *.tgz)

          # Push the versioned release
          helm push "$CHART_PACKAGE" "$REGISTRY_URL"
